name: "Wyoming VBAN Satellite"
description: "Use VBAN audio sources as Wyoming voice assistant satellites for Home Assistant"
version: "2.5.2"
slug: wyoming-vban-satellite
url: "https://github.com/powange/Wyoming-STT-VBAN"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
homeassistant_api: false
host_network: true
map:
  - config:rw
options:
  satellites:
    - name: "VBAN Satellite 1"
      wyoming_port: 10700
      vban_receive_port: 6980
      vban_receive_mode: "unicast"
      vban_receive_multicast_group: ""
      vban_receive_stream_name: ""
      tts_vban_enabled: false
      tts_vban_mode: "unicast"
      tts_vban_address: ""
      tts_vban_port: 6980
      tts_vban_stream_name: "TTS1"
  debug_logging: false

schema:
  satellites:
    - name: str
      wyoming_port: port
      vban_receive_port: port
      vban_receive_mode: "list(unicast|multicast)"
      vban_receive_multicast_group: str
      vban_receive_stream_name: str
      tts_vban_enabled: bool
      tts_vban_mode: "list(unicast|multicast)"
      tts_vban_address: str
      tts_vban_port: port
      tts_vban_stream_name: str
  debug_logging: bool
